apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: python-9524 
  janus-idp.io/tekton: python-9524
  backstage.io/kubernetes-id: python-9524
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: python-9524
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  