apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-9524-gitops
  description: This is GitOps manifest for python-9524   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: python-9524
    janus-idp.io/tekton: python-9524 
    backstage.io/kubernetes-id: python-9524 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:python-9524
